INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'enabled', 'TRUE');
INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'consumer_key', '');
INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'consumer_key_secret', '');
INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'social_login', 'FALSE');
INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'social_connection', 'FALSE');
INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'archive', 'TRUE');
INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'default_account', '');
INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'recent_videos_display', '4');
INSERT INTO `settings` VALUES(NULL, 1, 'youtube', 'recent_videos_link_actions', 'link');